version: "3"
services:
  profile:
    image: profileservice
    container_name: profile
    depends_on:
      - auth
    environment:
      - SERVER_PORT=8080
      - AUTH_URL=http://auth:8080
    ports:
      - 9090:8080
  auth:
    image: authservice
    container_name: auth
    environment:
      - SERVER_PORT=8080
    ports:
      - 8081:8080
  gateway:
    image: gatewayservice
    depends_on:
      - profile
      - auth
    environment:
      - SERVER_PORT=8080
      - PROFILE_URL=http://profile:8080
      - AUTH_URL=http://auth:8080
    ports:
      - 8080:8080
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS:
        PLAINTEXT://kafka:9092,
        PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
        PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1